[package]
name = "rust-screenshots"
version = "0.1.0"
edition = "2021"

[dependencies]
rdev ={ version = "0.5.3", features = ["unstable_grab"]}
screenshots = "0.8.5"
chrono = "0.4.31"
xcap = "0.2.2"

[profile.release]
lto = true
debug = 0
opt-level = "z"
panic = "abort"
strip = "symbols"
